### PR TITLE
Improve performance and flexibility

### PR DESCRIPTION
**Pull request by ChristopherSchultz**

### CODE REVIEW

**Comment by nayuki** [comment]
Sorry, I can't accept the quality of the code.

**Comment by ChristopherSchultz** [comment]
I can improve the patch. What seems to be the problem? Please consider all 3 commits together, as one commit needed to be added to restore something I believe my IDE did (replacing constant names with values) and another to remove some testing code.

I believe this is a legitimate improvement to the SVG-generation code you already had.

**Comment by nayuki** [comment]
At a glance, as an incomplete list of observations:

* You didn't restore the named constants MIN_VERSION and MAX_VERSION in all places.
* You left in test/debug code containing prints and timings.
* You altered the formatting on my existing code.
* Returning a `String` is good enough; it is unnecessary to accept a `PrintWriter`. The rest of the `QrCode` logic is slow enough already.

**Comment by ChristopherSchultz** [comment]
I will find and restore the additional constants. The test/debug code with prints and timings was intended to demonstrate that my changes were indeed productive. If I had included a commit removing those timings (the `main` method), you might have said that the performance changes weren't legitimate. The timings demonstrate that these changes improve the performance of `toSvgString` by an order of magnitude.

I will restore the tab-formatting. I still don't know why my IDE replaced all those constants. :(

The interface for `toSvgString` has not changed; it's been overloaded and by using `PrintWriter`, it can be streamed to a target. In my case, I am streaming it to a servlet client. There is no reason to build the complete string in memory. The use of `PrintWriter` does not add very much overhead; with all these changes the SVG conversion is still an order of magnitude faster than the original.

**Pull request closed without merging**
