### PR TITLE
add qr_segment_advanced module for the Rust code

### PR DESCRIPTION
**Pull request by magiclen**
The `QrSegmentAdvanced` class in Java code is awesome, so I ported them to Rust code.

### CODE REVIEW

**Comment by nayuki** [comment]
Wow, thanks for your contribution! I'm glad you showed me that porting QrSegmentAdvanced.makeSegmentsOptimally() and its child functions to Rust is quite neat and feasible. I like how your code is clean and idiomatic, and follows my existing code style pretty well. From your work, I learned that you can call static functions from the same struct impl by using `Self::foo()` instead of `MyType::foo()`. I might refactor a bunch of my existing Rust code to use this.

Some stylistic improvements for your future improvement:
* My code just jams words together for local variables (forexamplelikethis), because I use underscores for function/field members with a wider scope (for_example_like_this).
* You mirrored my Java code logic into Rust, but didn't copy any of the comments. I would synchronize the comments if I choose to publish this code.
* You initialized vectors with a fixed size and initial value fill to imitate my Java logic. But because I understand the algorithm, I would write the Rust code differently. I would instead start with an empty vector and push each tail element as it gets computed. This makes the intent more clear, and avoids initializing with dummy values.

But at the moment, I won't accept your code contribution because:
* The project readme says "This project aims to be the best, clearest QR Code generator library in multiple languages. The primary goals are flexible options and absolute correctness. Secondary goals are compact implementation size and good documentation comments.".
* The optimal segmentation algorithm is somewhat large, and I haven't decided if it should be included in the standard distribution or not. I included it in the advanced optional Java code (can easily delete the entire class) just to prove that it is possible.
* You silently (but correctly) dropped my kanji mode encoder. I haven't decided whether kanji mode is important or not.
* If I do include it in the standard distribution, then I need to add the algorithm for the other languages too: C, C++, JavaScript, TypeScript, Python. Lots more work for me to do.
* I'm not convinced that real-world data can benefit from mixed mode encoding. I usually see URLs which require byte mode, or pure numbers. It is rare to see good uses of alphanumeric mode. It is still rarer to see good kanji content.

**Comment by magiclen** [comment]
Thanks for your reply. I'm not a Japanese speaker and barely know Kanji. I skipped the Kanji part because I didn't want to do it in a sloppy and blind way (and also Kanji is totally useless for me and my cases).

I hope one day the remarkable optimal segmentation algorithm could be a formal feature of this library!

**Comment by nayuki** [comment]
Yeah, I noticed you're from Taiwan (cool country, by the way). Kanji is not hard for you, come on. ;-)

Side note - the Shift JIS set of kanji covers a lot of common Chinese characters. You can see this in my demo web page https://www.nayuki.io/page/optimal-text-segmentation-for-qr-codes if you select the last example containing Chinese text.

**Comment by magiclen** [comment]
I wrote `qr_segment_advanced` module instead of directly adding methods into `struct QrSegment`. And I also put **kanji** in `Cargo.toml` as a feature.

**Pull request closed without merging**
