### PR TITLE
Colour options and optimizations for drawCanvas

### PR DESCRIPTION
**Pull request by jawj**
This patch provides arguments for dark and light colours, and makes dramatic reductions in the number of `fillRect` calls required to draw the QR code (now the background colour is filled in one call, and any consecutive foreground-colour modules in the same row are coalesced into a single `fillRect` call too).

### CODE REVIEW

**Comment by nayuki** [comment]
Hi jawj, thanks for your effort in the patches. I first want to confirm this question with you: Did you see any performance issues with my JavaScript implementation of QR Code generation in practice? Is there a user-perceivable lag? If there is, what are the timings like? / Cheers, Nayuki

**Comment by jawj** [comment]
Thanks Nayuki. Perhaps you feel this is premature optimisation? It's true that I didn't see a problem, and no perceptible lag. However, I am using a recent MacBook and an iPhone 7 in testing. I expect some users to be using old Android devices, for example. It may be that those users experience no lag either. But I prefer to know that I am not causing easily-avoidable CPU work and energy use. 

My key motivation is that I am using the library within native iPhone and Android apps that run JS logic within JavaScriptCore, and translate JS <canvas> calls into native drawing calls. Every drawing call entails a trip across the JS/native boundary, which slows things down, so I was keen to reduce the number of fillRect calls, since this seemed easy to do.

**Comment by jawj** [comment]
You're right on the dark default — I was missing `ctx.fillStyle = dark || '#000000';`

Anyway, fair enough. I was attracted to this library because it seemed readable and thorough. I made some changes for my use case, and I thought I'd try contributing them back. No problem.

**Comment by nayuki** [comment]
No problem. Thanks for stopping by!

**Pull request closed without merging**
