### PR TITLE
no_std

### PR DESCRIPTION
**Pull request by FloVanGH**
Add optional no_std support to the rust crate.

### CODE REVIEW

**Comment by nayuki** [comment]
Please do not reformat my code. It makes it very difficult to audit what functional changes you made. I have a [style guide](https://www.nayuki.io/page/my-code-style) and willfully violating it is considered rude. I will not tolerate indentation tabs being changed to 4 spaces. Trailing spaces shall not be stripped. Long lines shall not be automatically re-wrapped.

First I should note that no_std was previously discussed in https://github.com/nayuki/QR-Code-generator/pull/58 .

It looks like what you did is add this block of code starting at line 85:

```rust
#![cfg_attr(not(feature = "std"), no_std)]

#[cfg(not(feature = "std"))]
#[macro_use]
extern crate alloc;

#[cfg(not(feature = "std"))]
use alloc::{string::*, vec::*};

#[cfg(not(feature = "std"))]
use core::{cmp, fmt, i32};

#[cfg(feature = "std")]
use std::{cmp, fmt, i32};
```

My fear is that in no_std environments like OS kernels and small microcontrollers, dynamic allocations are discouraged due to non-determinism and heap fragmentation. I don't think just renaming the library calls is the right approach. I feel that if I were to make a Rust no_std implementation, I would mimic what I did in my C version where every function takes in a caller-allocated buffer and performs all intermediate and final work on those buffers, with absolutely no heap allocation within the library at all. The caller can choose to stack-allocate or heap-allocate those buffers as it sees fit.

**Comment by FloVanGH** [comment]
Ok thank you for your feedback. It es was not my intention to reformat your code, it was a mistake, sorry about that.

I'm working on a no_std ui toolkit on Rust and use there also dynamic allocation without a problem. My intention behind my MR that I want to use your crate to create a qr widget for my toolkit. But I can understand your concerns. I will continue using my fork of your crate and will check the no_std and your crate later.
Thank you

**Comment by nayuki** [comment]
Okay, that's fine. You're more than welcome to do what you want in your own fork.

(MR = merge request, I guess)

**Comment by FloVanGH** [comment]
Yes MR (Merge Request) 😄. I curious to see the result of your no_std solution.

**Comment by nayuki** [comment]
See https://github.com/nayuki/QR-Code-generator/pull/58#issuecomment-691512756 . Again, reiterating my intentions:

> I feel that if I were to make a Rust no_std implementation, I would mimic what I did in my C version where every function takes in a caller-allocated buffer and performs all intermediate and final work on those buffers, with absolutely no heap allocation within the library at all. The caller can choose to stack-allocate or heap-allocate those buffers as it sees fit.

**Comment by FloVanGH** [comment]
Thank your that's helpful. I made me more clear why dynamic allocation could be problematic in some cases.

**Comment by nayuki** [comment]
Today's initial commit of a Rust no-heap no_std implementation: https://github.com/nayuki/QR-Code-generator/tree/d8ea85f2e2a62852217b71151029cee7cc019139

**Pull request closed without merging**
