### PR TITLE
Fixes deprecated use of URI # on chrome 72

### PR DESCRIPTION
**Pull request by zahnno**
Addresses: https://github.com/nayuki/QR-Code-generator/issues/49

### CODE REVIEW

**Comment by nayuki** [comment]
Hi zahnno (Toronto person!). I searched on the web, and unfortunately could not find any articles to substantiate your claim or your change.

There is no mention of Chrome (72) deprecating a particular URI hash syntax or SVG color syntax. The closest page I can find is: https://developers.google.com/web/updates/2018/12/chrome-72-deps-rems

There is evidence that the hex #ABCDEF color syntax will be supported in SVG forever: https://www.w3.org/TR/SVGColor12/#sRGBcolor

Please explain yourself.

**Comment by nayuki** [comment]
Doing some more digging, it looks like this syntax issue arises only if you cram the SVG text into a "data:" URI without doing the proper escaping. And indeed, Chrome 72 is giving warnings. See:
* https://stackoverflow.com/questions/50615029/unescaped-characters-in-a-data-uri-body-deprecated-how-to-find-in-project/50696068
* https://github.com/stylus/stylus/issues/2379
* https://www.chromestatus.com/features/5656049583390720

I have not violated any rules by outputting legal SVG files. Whoever is consuming the text is responsible for appropriately calling `encodeURIComponent()` before injecting it into a URI.

Absent further evidence, I am strongly in favor of WONTFIX.

**Comment by zahnno** [comment]
It's not throwing warnings, it's not rendering the SVG. If the fill attribute on your generated SVG isn't compatible with hex color, when crammed into a 'data:', I don't see why you wouldn't change it to an rbg.

**Comment by nayuki** [comment]
From what I understand, a "data:" URI only allows certain ASCII characters to be present. Characters outside the safe set (which I don't know exactly what it is) could cause different behavior in different browsers or versions.

I believe that `#` is an unsafe character in a data-URI (unless the URI encodes an HTML page, and the # is used to specify an anchor to jump to?). There are probably other unsafe characters as well (maybe `?&":/%`), which could potentially be used in my SVG output now or in the future.

Hence, I suggest that the correct universal solution is to call `encodeURIComponent()` on my SVG text output before injecting it into a URI.

**Comment by nayuki** [comment]
See what I did in this new feature: https://github.com/nayuki/QR-Code-generator/commit/22fac31bdf81da68730c177c0e931c93234d2a30

https://github.com/nayuki/QR-Code-generator/blob/22fac31bdf81da68730c177c0e931c93234d2a30/typescript-javascript/qrcodegen-input-demo.ts#L108

**Pull request closed without merging**
