### PR TITLE
correction in penalty calculation

### PR DESCRIPTION
**Pull request by meirumeiru**
hi, I think, that according to the QR standard (at least in the version of 2006), the calculation of then penalties is done a little bit different (it doesn't make much sense, the way they do it, but... still... maybe you want to have a look at it)

### CODE REVIEW

**Comment by nayuki** [comment]
Thanks for your suggestion. I'm pretty sure I was using the 2005 version of the QR standard rather than the 2015 version. The calculation of penalties was a bit ambiguous with regards to ordering, so I did my best to understand the intentions behind the calculation. I believe my interpretation is the best - because ultimately, the amount of problems in a QR Code is based on the final rendered form with all bits painted, rather than some intermediate form where the format bits have a placeholder. Hence, I believe I need to change the code in a different way than you wrote.

The other change you suggested, regarding `finderPenaltyCountPatterns()`, appears to be incorrect. The reason I'm using `+` instead of `|` is because the finder pattern can appear on either the left side or right side *or both*, and I interpreted that overlapping matches are valid for scoring.

**Comment by meirumeiru** [comment]
> ... I was using the 2005 version of the QR standard

that's the one I use too

> The calculation of penalties was a bit ambiguous with regards to ordering, so I did my best to understand the intentions behind the calculation. I believe my interpretation is the best - because ultimately, the amount of problems in a QR Code is based on the final rendered form with all bits painted, rather than some intermediate form where the format bits have a placeholder.

you're right... the solution of the standard isn't optimal... I just saw, that you didn't do it according to the standard (you can see what they do from the pictures they added when they explained the calculation) and thought, I'll tell you... maybe (that's at least what I will do in my code) you want to add an #if/#else to the code to have both versions in... once the pure standard, once the better solution... and I've heard, that they are currently open for changes to this standard... so, maybe they'll change it anyway

> The other change you suggested, regarding `finderPenaltyCountPatterns()`, appears to be incorrect. The reason I'm using `+` instead of `|` is because the finder pattern can appear on either the left side or right side _or both_, and I interpreted that overlapping matches are valid for scoring.

well, that's a strange one, because I'm calculating it completely different and I have exactly the same values you have when I add a '|' instead of a '+' ... don't you count those patters twice otherwise?

... yeah... not so important :-)

**Comment by nayuki** [comment]
> they are currently open for changes to this standard... so, maybe they'll change it anyway

I have a copy of the year-2015 standard but didn't read it. I doubt it has any changes in the areas we're talking about.

> I'm calculating it completely different and I have exactly the same values you have when I add a '|' instead of a '+'

To trigger a difference in the N3 penalty calculation, you'll need a pattern of modules like: □□□□■□■■■□■□□□□. In other words, it's a two-sided finder, because it has a quiet zone of at least 4 modules on both the left and right sides.

**Comment by meirumeiru** [comment]
> > I'm calculating it completely different and I have exactly the same values you have when I add a '|' instead of a '+'
> 
> To trigger a difference in the N3 penalty calculation, you'll need a pattern of modules like: □□□□■□■■■□■□□□□. In other words, it's a two-sided finder, because it has a quiet zone of at least 4 modules on both the left and right sides.

yes... right (I had this multiple times now with my recent tests... sometimes even 3-4 times in the same code)... and this pattern is what I count as 1, while you count it as 2... correct? ... so, here's the difference, but... I've no idea what the "correct" or "intended" way was

I did read it like "the pattern must be present and on at least one side you must have 4 white spaces" :-) ... because, I don't think it's making the outcome worse, if it has white spaces on both sides... it's a pattern that can be recognized... and that's the problem... but, that's just my interpretation :-)

... so, up to you, what you want to do. It's just an input (I'm always complaining about people not reporting what the think about open source software and not discussing it, because this doesn't produce any improvements and is not the idea of open source... that's why I thought, I should tell you... and, after all, your code helped me to detect my N4 penalty bug).

**Comment by nayuki** [comment]
> this pattern is what I count as 1, while you count it as 2... correct? [...] I've no idea what the "correct" or "intended" way was [...]  I don't think it's making the outcome worse, if it has white spaces on both sides

When reading the QR spec, I interpreted the intent is to identify how many valid finder patterns can be found. The finder pattern is directional because it should tell you which side has the potential QR Code and which side is the outside world. Namely, the side with the 4 light modules is probably the outside world. If both sides have 4 light modules, then the scanner application would need to check both sides for a potential QR Code, hence why I count a double penalty.

> It's just an input

Thanks, I appreciate that your report has some depth to it and you proposed some plausible code changes. The kind of input that I hate are basic help requests and people who show no effort.

> your code helped me to detect my N4 penalty bug

It's great that you are commenting on my work because you've replicated much of it on your own. I guess your level of background knowledge is very high, then.

**Comment by nayuki** [comment]
In case you haven't heard of this web page: https://www.nayuki.io/page/creating-a-qr-code-step-by-step

> This JavaScript demo application visualizes in detailed steps, how a text string is encoded into a QR Code barcode symbol. The content of this page essentially explains and justifies how my QR Code generator library works internally.

Note that in section 8, the web app visually draws boxes to show which QR Code modules are triggering penalty points.

**Comment by meirumeiru** [comment]
> It's great that you are commenting on my work because you've replicated much of it on your own. I guess your level of background knowledge is very high, then.

Yes, my first implementation is from about 12 to 14 years ago (I don't remember correctly, all I know is that the first check-in to my current code reposistory is from 2016).

**Comment by meirumeiru** [comment]
> In case you haven't heard of this web page: https://www.nayuki.io/page/creating-a-qr-code-step-by-step
> 
> > This JavaScript demo application visualizes in detailed steps, how a text string is encoded into a QR Code barcode symbol. The content of this page essentially explains and justifies how my QR Code generator library works internally.
> 
> Note that in section 8, the web app visually draws boxes to show which QR Code modules are triggering penalty points.

Very interesting...

And, you're thoughts are very good... but I'm still not sure if I'd vote for double counting it :-) ... currently I'm completely undecided. Why? Well, let's say you have 2 such patterns inside the data and an other mask has 1 with both sides white... or even better an other mask produces 2 empty spaces near the original finder patterns... is this then worse than the first one? ... I guess we could talk for very long about it... maybe I'm first going to write my first decoder before I try to answer this. But, luckily it's just 1 character that has to be changed to switch from one mode to the other.

Anyway... :-)

**Comment by nayuki** [comment]
> I'm still not sure if I'd vote for double counting it

Don't forget that finder-like patterns are counted separately when found horizontally vs. vertically. Orientation matters, and I believe there are 4 orientations to consider, not 2.

For reference, here is the relevant quote from the QR 2005 spec, page 54:

**Comment by meirumeiru** [comment]
yeah... and that's the point which is my problem...
they talk about the 1:1:3:1:1 pattern, preceded or followed ... (ok, they say or, not or/and) but then they say "existence of the pattern" ... and I interpreted this as the "existence of the 1:1:3:1:1 pattern"... but, you're also right, because the pattern is also ignored, when there's no light area... so they might think of the "pattern" as the whole, including the light area :-) ...

**Pull request closed without merging**
