### PR TITLE
QrCode Renderer

### PR DESCRIPTION
**Pull request by chubbard**
Adds a class that encapsulates rendering QRCodes to BufferedImage, bitmap to a java.lang.File, SVG, and bitmaps to OutputStream.  This makes it really simple to render QRCode out of the box without needing understand the details of graphics, image formats, and details of the library.  Here is a simple example:

```
 QrCode qr = QrCode.encodeText( "Hello World!", QrCode.Ecc.MEDIUM );
 File target = new QrCodeRenderer().renderFile(qrCode, "png", new File("output.png"));
```

### CODE REVIEW

**Comment by chubbard** [comment]
For your review to enhance QR-Code-Generator with out of the box rendering.

**Comment by nayuki** [comment]
Image output is a feature that was removed several years ago to avoid favoring any particular format. Please consult the commit history.

**Comment by chubbard** [comment]
This would make your library more developer friendly.  Why not include it?  It would be like going to a sushi restaurant and they tell you they removed the rice from their sushi because they didn't want you to favor any particular rice.  So you need to bring your own rice.  Pretty sure people would see that as obtuse logic bordering on illogical and not a real reason to remove the rice.  Plus including a mechanism to render the QR Code doesn't prevent anyone from making their own version should they see fit to do that.  Obviously if I can create this representation anyone has the ability to create additional renderers.  By including this renderer you aren't stopping people from making other renderers.

**Comment by chubbard** [comment]
I appreciate keeping the feature set minimized to keep the library focused on doing one thing well and keeping it practically oriented.  But, I don't see this as more is better, but more keeps it targeted towards practicality.  The library is not useful until you can visualize the QrCode.  That's the minimal feature set that delivers something useful.  Or more straight forwardly stated allows the consumer of this lib to deliver their feature.  This addition would only help fulfill the needs of what most people require.  This PR just takes a stab about what is most likely to be required.  Your point about `java.awt.BufferedImage` is valid, but there are solutions to it.  I can tell you are tired of explaining your decision over and over, but if you have to keep explaining it maybe it's important and could warrant reconsidering your position.  There is a difference between being opinionated and obstinate, and usually the difference is misplaced dogma.

In the end if you reject this PR, which is well within your right to do so, I can release it as a separate library that uses your lib to make it easier for people to consume.

**Pull request closed without merging**
