### PR TITLE
Changes for Java6 compatibility.

### PR DESCRIPTION
**Pull request by guillerodriguez**
Not sure if this is useful or wanted, but here are a few changes that make the code compatible with Java6 (and Android). They are all pretty minor except perhaps for the addition of a Base64 decoder class.

### CODE REVIEW

**Comment by nayuki** [comment]
Platform major release dates:
* Java SE 5: 2004-09-30
* Java SE 6: 2006-12-11
* Java SE 7: 2011-07-28
* Java SE 8: 2014-03-18
* Java SE 9: 2017-09-21
* Java SE 10: 2018-03-20

**Comment by nayuki** [comment]
* Java SE 6 is *very* old, and I hope nobody is still using it for development. Java SE 7 is old too, but I've seen OS package managers that were slow to adopt 8, so I consciously designed my QR Code generator library to target 7.
* I used Java 7 APIs such as StandardCharsets and Objects.requireNonNull(). For the optional QrSegmentAdvanced functionality, I used the Java 8 API of Base64.
* I am not sure what you are trying to achieve by supporting Java 6. Who is the target audience? Who will benefit from this?
* I have looked briefly into Android API levels in the past, such as in [another discussion](https://github.com/nayuki/QR-Code-generator/pull/8). Are you saying that some Java APIs I use are not in Android at all? Or are you targeting a particular past version of the Android API?
* Though I haven't scrutinized every line of code, I will give you the benefit of the doubt that your patch works as intended. Even so, it is a substantial and jarring change to my codebase by adding new classes and hundreds of lines of code, with a negative impact on conciseness and consistency. Also, your choice to comment out certain lines of code instead of removing them outright is not good style. No attempt was made to explain the benefit of supporting Java 6 or some unspecified Android API version. Why should these changes be accepted?

**Comment by guillerodriguez** [comment]
Hi,

The main use case for Java SE 6 support is Android -- not all API levels support the Objects and StandardCharsets APIs. Another use case is embedded devices running Java6-compatible platforms (this was actually my case). Most of the required changes are trivial, including:

 * Supplying an implementation for Objects.requireNonNull and StandardCharsets.US_ASCII and UTF_8
 * Replacing the diamond operator with an explicit type specification
 * Replacing try-with-resources with explicit try / finally blocks

The only thing that is not trivial is the Base64 dependency in QrSegmentAdvanced. I don't use this myself and I only added this for completeness. I'm happy to remove it from the PR if you want since as you say this class is optional anyway.

Re. the commenting out of lines of code instead of removing them outright: Yes you are right. This is a one minute change though so I just did it.

So, "Why should these changes be accepted?". Well, you don't have to of course :) But since the changes are so small (with the exception of the Base64 stuff), it may make sense.

If you are interested, let me know and I will revert the Base64 stuff in the PR.

**Comment by guillerodriguez** [comment]
Uhm, ok. But why do you ask questions if you don't even bother commenting on the answers?

Thanks for your nice work anyway.

**Pull request closed without merging**
