### PR TITLE
Made Java implementation modularized

### PR DESCRIPTION
**Pull request by mariotaku**
This PR made following changes:

1. Migrated to gradle project
2. Backported Objects.requireNonNull from Java 7 to make lib works on most platforms (espacially Android)
3. Separated platform specific code into other module
4. Added Android support (encode to Bitmap)

### CODE REVIEW

**Comment by nayuki** [comment]
[Objects.requireNonNull()](https://docs.oracle.com/javase/7/docs/api/java/util/Objects.html#requireNonNull(T)) is from Java SE 7, not 8.

**Comment by mariotaku** [comment]
@nayuki Oops, sorry, I'll change. Reason I backported this is Android doesn't support methods from Java 7 until API 19 (KitKat)

**Comment by glitchammer** [comment]
For objects.requireNotNull() method you can use @NonNull annotation for method args. Anyway, the call to StandardCharset.* on Android works only since sdk version 19 (as you said), which should be fine, but by default, Android Studio sets minSdk to 15 at this point of time. Current sdk version is at 25. Have a look at my fork if you like.

**Comment by nayuki** [comment]
@glitchammer Actually I have a clarification request. **Which** `@NonNull` annotation are you recommending? I did a bit of [research](https://stackoverflow.com/questions/4963300/which-notnull-java-annotation-should-i-use) recently, and NonNull didn't make it into Java SE at all. I only see a bunch of third-party libraries, none of which seem unambiguously popular.

**Comment by mariotaku** [comment]
[JetBrains Annotations](https://www.jetbrains.com/help/idea/nullable-and-notnull-annotations.html) seems to be a good choice.

**Pull request closed without merging**
