### PR TITLE
Refactoring, design pattern, testing

### PR DESCRIPTION
**Pull request by gerzees**

### CODE REVIEW

**Comment by nayuki** [comment]
Is this your school assignment?

**Comment by gerzees** [comment]
> Is this your school assignment?

Yes, it was.

**Comment by nayuki** [comment]
The code in your pull request does not meet my quality standards. For example:
* You needlessly added many lines of code and files which do not serve a useful purpose.
* You slavishly follow [design patterns](https://en.wikipedia.org/wiki/Software_design_pattern) that make the code harder, not easier to understand.
* Your code style is not consistent in naming, capitalization, spacing, or blank lines.
* You split up / refactored functions in a way that makes them harder to read.
* You have commits with meaningless test messages like "hello" and "final commit 2".
* You renamed variables in a way that creates shadowing/conflicts and makes them much more verbose without improving overall clarity.

It is okay for you to keep this set of commits private to your group.
It is not okay to contribute this low-quality work back to the original author, taking up their time to review and handle it.
If your teacher required you to open a pull request to the original author, please tell them that it is an unreasonable requirement.

**Comment by gerzees** [comment]
I apologize to you that I opened a pull request which took up your time and has low-quality work. 
I appreciate your advice and I'll keep it in my mind.

**Pull request closed without merging**
