### PR TITLE
Repackaged as a Maven library

### PR DESCRIPTION
**Pull request by tovine**
This can now be included as a dependency in Maven projects and downloaded directly from the Maven Central Repository.

### CODE REVIEW

**Comment by tovine** [comment]
Here is the link to the project in Maven Central: http://search.maven.org/#artifactdetails%7Ccom.github.nayuki%7Cqrcodegen%7C1.0.0%7Cjar

**Comment by tovine** [comment]
If you think this is a nice thing to have I can probably take the responsibility of packaging any new versions you want to release as well, just let me know. :)

**Comment by chrylis** [comment]
This would be immensely helpful to have!

**Comment by tovine** [comment]
I won't be maintaining the Maven package or my fork anymore as I have switched jobs.
I can however be of assistance to anyone who wishes to take over and continue maintaining it (either as a separate fork or as part of @nayuki's official repo), just let me know.

**Comment by nayuki** [comment]
Thanks for the update, tovine. Coincidentally a week before your message, I started learning how to use Maven to package and publish this library. Tonight my work is done: https://search.maven.org/artifact/io.nayuki/qrcodegen/1.4.0/jar

You might want to take a look at the [POM file](https://github.com/nayuki/QR-Code-generator/blob/8e54f6ffa656520ca85d4d58b7970a3e35bf0bed/java/pom.xml) to see how I preferred to do things. Cheers, and thanks again for showing me this work is feasible.

**Comment by tovine** [comment]
Ok, I'm closing this pull request then.
You might want to enable more notifications if you didn't see the PR in the last 9 months though, could have saved you some of the work... :)

**Comment by nayuki** [comment]
I saw this notification within a few weeks of you posting it. But I wasn't sure what to do with it, because at the time I didn't want to spend a few evenings reading up on Maven, installing things, and learning and experimenting with the workflow. So I brushed the topic aside and made a mental note to come back later.

**Pull request closed without merging**
